POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
    "body": 12,
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
    "body": "sample"
}

###

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
    "body": "This is an opinion I need to share with the world. This is an opinion I need to share with the world. This is an opinion I need to share with the world. This is an opinion I need to share with the world. This is an opinion I need to share with the world"
}

###

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is a kerfuffle opinion I need to share with the world"
}

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "password": "04234",
  "email": "cvc.comanescu.catalin@gmail.com"
}

###

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "password": "04234",
  "email": "cvc.comanescu.catalin@gmail.com"
}

###

POST http://localhost:8080/admin/reset HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiN2UyYWNiMTgtN2I1MS00NWM0LThkMzYtODBkOTZlMWVjMzhmIiwiZXhwIjoxNzM4NjIxMzYwLCJpYXQiOjE3Mzg2MTc3NjB9.MV3-oLxsubIo3g-8Axqx2rYvjbUjryc_fMR3L0neUfc

{
  "body": "Hello, world! hhhhh"
}

###

GET http://localhost:8080/api/chirps HTTP/1.1

###

GET http://localhost:8080/api/chirps/6c6aacc7-ccb5-42a3-8bcf-735f1f14f61c HTTP/1.1